algo = input('Digite Algo:')
print('O tipo primitivo desse valor é',type,algo)
print('Só tem espaços?',algo.isspace())
print('É um numero?',algo.isnumeric())
print('É alfaberico?',algo.isalpha())
print('É alfanumerico?',algo.isalnum())
print('Está Maiusculas?',algo.isupper())
print('Está Minusculas?',algo.islower())
print('Está Capitalizada?',algo.istitle())